#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
관리할 유니티 프로젝트들이 들어 있는 디렉터리(Projects 디렉터리)와, 
출력(클론)할 디렉터리(Output 디렉터리), 그리고 블랙리스트 목록을 입력받아
1) 각 프로젝트에 .gitignore 설정 및 초기화
2) 최종적으로 Git Clone하여 Output 디렉터리에 복제

Usage:
  python batch_convert_unity_projects.py --projects_dir "C:/UnityProjects" --output_dir "C:/Output" --blacklist "ProjectA,ProjectB"

※ 주의사항
- Git이 설치되어 있어야 하며, PATH에 등록되어 있어야 합니다.
- 블랙리스트의 이름은 디렉터리와 정확히 일치할 때만 제외합니다.
"""

import os
import sys
import argparse
import subprocess

is_test = False

UNITY_GITIGNORE = r"""
# This .gitignore file should be placed at the root of your Unity project directory
#
# Get latest from https://github.com/github/gitignore/blob/main/Unity.gitignore
#
.utmp/
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/
*.log

# By default unity supports Blender asset imports, *.blend1 blender files do not need to be commited to version control.
*.blend1
*.blend1.meta

# MemoryCaptures can get excessive in size.
# They also could contain extremely sensitive data
/[Mm]emoryCaptures/

# Recordings can get excessive in size
/[Rr]ecordings/

# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider plugin
/[Aa]ssets/Plugins/Editor/JetBrains*
# Jetbrains Rider personal-layer settings
*.DotSettings.user

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Mono auto generated files
mono_crash.*

# Builds
*.apk
*.aab
*.unitypackage
*.unitypackage.meta
*.app

# Crashlytics generated file
crashlytics-build.properties

# TestRunner generated files
InitTestScene*.unity*

# Addressables default ignores, before user customizations
/ServerData
/[Aa]ssets/StreamingAssets/aa*
/[Aa]ssets/AddressableAssetsData/link.xml*
/[Aa]ssets/Addressables_Temp*
# By default, Addressables content builds will generate addressables_content_state.bin
# files in platform-specific subfolders, for example:
# /Assets/AddressableAssetsData/OSX/addressables_content_state.bin
/[Aa]ssets/AddressableAssetsData/*/*.bin*

# Visual Scripting auto-generated files
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db.meta
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers.meta

# Auto-generated scenes by play mode tests
/[Aa]ssets/[Ii]nit[Tt]est[Ss]cene*.unity*
"""


def parse_args():
    parser = argparse.ArgumentParser(description="Manage multiple Unity projects with Git initialization and .gitignore.")
    parser.add_argument(
        "--projects_dir",
        required=True,
        help="Input directory where all the unity projects resides"
    )
    parser.add_argument(
        "--output_dir",
        required=True,
        help="Output directory where all the postprocessed projects to be saved"
    )
    parser.add_argument(
        "--blacklist",
        default="", 
        help="Any children in the input directory that will be excluded from this batch conversion"
    )
    return parser.parse_args()


def is_git_repo(directory: str) -> bool:
    """check if this directory is a Git repository"""
    git_dir = os.path.join(directory, ".git")
    return os.path.isdir(git_dir)


def has_gitignore(directory: str) -> bool:
    """check if this directory has a .gitignore file"""
    gitignore_path = os.path.join(directory, ".gitignore")
    return os.path.isfile(gitignore_path)


def is_in_blacklist(project_name: str, blacklist_list: list[str]) -> bool:
    """
    check if the directory is enlisted in the blacklist
    """
    for item in blacklist_list:
        trimmed_item = item.strip()
        if project_name == trimmed_item:
            return True
    return False


def main():
    args = parse_args()

    projects_dir = args.projects_dir
    output_dir = args.output_dir
    blacklist_str = args.blacklist.strip()

    blacklist_list = []
    if blacklist_str:
        blacklist_list = [x for x in blacklist_str.split(",") if x.strip()]

    if not os.path.isdir(projects_dir):
        print(f"[Error] Projects Directory does not exist: {projects_dir}")
        sys.exit(1)

    # output_dir이 없으면 생성
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    # --- 1. 프로젝트 폴더들을 순회하며 Git 초기화 및 .gitignore 설정 ---
    for entry in os.scandir(projects_dir):
        if not entry.is_dir():
            continue

        project_path = entry.path
        project_name = entry.name

        if is_in_blacklist(project_name, blacklist_list):
            print(f"[SKIP] '{project_name}' is enlisted in the blacklist. Skipping.")
            continue

        if not is_git_repo(project_path):
            print(f"[INFO] Execute '{project_name}' → git init")
            try:
                subprocess.run(["git", "-C", project_path, "init"], check=True)
            except subprocess.CalledProcessError as e:
                print(f"[Error] git init failed: {e}")
                continue

            print(f"[INFO] Appending '{project_name}' → .gitignore")
            gitignore_file = os.path.join(project_path, ".gitignore")
            with open(gitignore_file, "w", encoding="utf-8") as f:
                f.write(UNITY_GITIGNORE)

            try:
                subprocess.run(["git", "-C", project_path, "add", ".gitignore"], check=True)
                subprocess.run(["git", "-C", project_path, "commit", "-m", "Add Unity .gitignore"], check=True)
            except subprocess.CalledProcessError as e:
                print(f"[Error] .gitignore add/commit failed: {e}")
                continue

            try:
                subprocess.run(["git", "-C", project_path, "add", "."], check=True)
                subprocess.run(["git", "-C", project_path, "commit", "-m", "Initial commit"], check=True)
            except subprocess.CalledProcessError as e:
                print(f"[Error] committing other files failed: {e}")
                continue

        else:
            if not has_gitignore(project_path):
                print(f"[INFO] Appending '{project_name}' → .gitignore")
                gitignore_file = os.path.join(project_path, ".gitignore")
                with open(gitignore_file, "w", encoding="utf-8") as f:
                    f.write(UNITY_GITIGNORE)

                try:
                    subprocess.run(["git", "-C", project_path, "add", ".gitignore"], check=True)
                    subprocess.run(["git", "-C", project_path, "commit", "-m", "Add Unity .gitignore"], check=True)
                except subprocess.CalledProcessError as e:
                    print(f"[Error] .gitignore add/commit failed: {e}")
                    continue
            else:
                print(f"[INFO] '{project_name}' → Already is git repository, and possesses a .gitignore.")
        
        if is_test:
            wait()

    print("------------------------------------------------------------")
    print("[INFO] Git init and .gitignore for targetted projects finished.")
    print("------------------------------------------------------------")

    # --- 2. 다시 블랙리스트에 포함되지 않은 프로젝트를 순회, Git Clone 수행 ---
    for entry in os.scandir(projects_dir):
        if not entry.is_dir():
            continue

        project_path = entry.path
        project_name = entry.name

        if is_in_blacklist(project_name, blacklist_list):
            continue

        if is_git_repo(project_path):
            clone_target = os.path.join(output_dir, project_name)
            print(f"[INFO] Cloning '{project_name}' → '{clone_target}'")

            # ===================================================
            # if required, do something else other than skipping
            if os.path.exists(clone_target):
                print(f"[WARNING] Skipping as the output folder already exists: {clone_target}")
                continue
            # ===================================================

            try:
                subprocess.run(["git", "clone", project_path, clone_target], check=True)
            except subprocess.CalledProcessError as e:
                print(f"[Error] '{project_name}' clone failed: {e}")
                continue
        else:
            print(f"[WARNING] '{project_name}' is not a Git repository. Clonning is skipped.")
        
        if is_test:
            wait()

    print("------------------------------------------------------------")
    print("[INFO] Execution Complete.")
    print("------------------------------------------------------------")


import msvcrt as m
def wait():
    m.getch()


if __name__ == "__main__":
    main()

r"""
# how to run:
```
python main.py `
  --projects_dir "D:/Unity Projects/92. 버림" `
  --output_dir "D:/Unity Project Compressed/92. 버림" `
```

--blacklist "90. 개인 연습,91. 개인 작업,92. 버림,98. Others,AMASSPlayer-main,AMASSPlayer-main_2,AnimationCurveExtractAndRecord,BoneHierarchy,Bowling Scene,Catchball_도형9,Catchball8,GestureNet,IKPlayground,IoTMockUp,J_AMASSPlayer,J_AMASSPlayer6,LeanWalkTest,portals-urp,pun2testforik,ReliableNetworkProject,SentisTest,SMPL2GameRig,SMPLX-Unity,TrigonIK,uma2,VR,VRDemo"
cmd인 경우 ^를 \로 대체
"""