#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
관리할 유니티 프로젝트들이 들어 있는 디렉터리(Projects 디렉터리)와, 
출력(클론)할 디렉터리(Output 디렉터리), 그리고 블랙리스트 목록을 입력받아
1) 각 프로젝트에 .gitignore 설정 및 초기화
2) 최종적으로 Git Clone하여 Output 디렉터리에 복제

Usage:
  python manage_unity_projects.py --projects_dir "C:/UnityProjects" --output_dir "C:/Output" --blacklist "ProjectA,ProjectB"

※ 주의사항
- Git이 설치되어 있어야 하며, PATH에 등록되어 있어야 합니다.
- 블랙리스트의 이름은 디렉터리와 정확히 일치할 때만 제외합니다.
"""

import os
import sys
import argparse
import subprocess

is_test = False

# --- 1. 유니티용 .gitignore 내용 사전 정의 (GitHub Unity.gitignore 템플릿 일부/전체) ---
# 필요에 따라 내용 축약/수정 가능
UNITY_GITIGNORE = r"""
# This .gitignore file should be placed at the root of your Unity project directory
#
# Get latest from https://github.com/github/gitignore/blob/main/Unity.gitignore
#
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/

# MemoryCaptures can get excessive in size.
# They also could contain extremely sensitive data
/[Mm]emoryCaptures/

# Recordings can get excessive in size
/[Rr]ecordings/

# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider plugin
/[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage
*.unitypackage.meta
*.app

# Crashlytics generated file
crashlytics-build.properties

# Packed Addressables
/[Aa]ssets/[Aa]ddressable[Aa]ssets[Dd]ata/*/*.bin*

# Temporary auto-generated Android Assets
/[Aa]ssets/[Ss]treamingAssets/aa.meta
/[Aa]ssets/[Ss]treamingAssets/aa/*
"""


def parse_args():
    """
    스크립트 실행 시 필요한 인자를 파싱합니다.
    예시:
      python manage_unity_projects.py --projects_dir "C:/UnityProjects" --output_dir "C:/Output" --blacklist "ProjectA,ProjectB"
    """
    parser = argparse.ArgumentParser(description="Manage multiple Unity projects with Git initialization and .gitignore.")
    parser.add_argument(
        "--projects_dir",
        required=True,
        help="(필수) 여러 유니티 프로젝트가 들어 있는 상위 디렉터리 경로"
    )
    parser.add_argument(
        "--output_dir",
        required=True,
        help="(필수) 클론된 프로젝트들이 저장될 위치"
    )
    parser.add_argument(
        "--blacklist",
        default="", 
        help="(옵션) 블랙리스트 목록. 쉼표(,)로 구분된 프로젝트 폴더 이름들"
    )
    return parser.parse_args()


def is_git_repo(directory: str) -> bool:
    """해당 디렉터리가 git 저장소인지(.git 폴더 존재 여부) 확인"""
    git_dir = os.path.join(directory, ".git")
    return os.path.isdir(git_dir)


def has_gitignore(directory: str) -> bool:
    """해당 디렉터리에 .gitignore 파일이 존재하는지 확인"""
    gitignore_path = os.path.join(directory, ".gitignore")
    return os.path.isfile(gitignore_path)


def is_in_blacklist(project_name: str, blacklist_list: list[str]) -> bool:
    """
    프로젝트 이름이 블랙리스트에 포함되어 있는지 확인
    블랙리스트 문자열들을 양쪽 공백 제거 후(트림) 비교
    """
    for item in blacklist_list:
        trimmed_item = item.strip()
        if project_name == trimmed_item:
            return True
    return False


def main():
    # --- 인자 파싱 ---
    args = parse_args()
    projects_dir = args.projects_dir
    output_dir = args.output_dir
    blacklist_str = args.blacklist.strip()

    # --- 블랙리스트 처리 ---
    # 쉼표로 구분된 문자열을 배열로 변환
    blacklist_list = []
    if blacklist_str:
        blacklist_list = [x for x in blacklist_str.split(",") if x.strip()]

    # --- 0. 경로 유효성 체크 ---
    if not os.path.isdir(projects_dir):
        print(f"[Error] Projects Directory가 존재하지 않습니다: {projects_dir}")
        sys.exit(1)

    # output_dir이 없으면 생성
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    # --- 1. 프로젝트 폴더들을 순회하며 Git 초기화 및 .gitignore 설정 ---
    for entry in os.scandir(projects_dir):
        if not entry.is_dir():
            continue

        project_path = entry.path
        project_name = entry.name

        # 블랙리스트 체크
        if is_in_blacklist(project_name, blacklist_list):
            print(f"[SKIP] '{project_name}'은(는) 블랙리스트에 포함되어 처리하지 않습니다.")
            continue

        # 1-1. Git 저장소 여부 확인
        if not is_git_repo(project_path):
            # 아직 git init이 안 된 경우
            print(f"[INFO] '{project_name}' → git init 실행")
            try:
                subprocess.run(["git", "-C", project_path, "init"], check=True)
            except subprocess.CalledProcessError as e:
                print(f"[Error] git init 실패: {e}")
                continue

            # .gitignore 파일 생성
            gitignore_file = os.path.join(project_path, ".gitignore")
            with open(gitignore_file, "w", encoding="utf-8") as f:
                f.write(UNITY_GITIGNORE)

            # .gitignore 커밋
            try:
                subprocess.run(["git", "-C", project_path, "add", ".gitignore"], check=True)
                subprocess.run(["git", "-C", project_path, "commit", "-m", "Add Unity .gitignore"], check=True)
            except subprocess.CalledProcessError as e:
                print(f"[Error] .gitignore add/commit 실패: {e}")
                continue

            # 나머지 파일을 .gitignore 규칙에 따라 스테이지 및 커밋
            try:
                subprocess.run(["git", "-C", project_path, "add", "."], check=True)
                subprocess.run(["git", "-C", project_path, "commit", "-m", "Initial commit"], check=True)
            except subprocess.CalledProcessError as e:
                print(f"[Error] 나머지 파일 commit 실패: {e}")
                continue

        else:
            # git init은 되어 있는데, .gitignore가 없으면 추가
            if not has_gitignore(project_path):
                print(f"[INFO] '{project_name}' → .gitignore 추가")
                gitignore_file = os.path.join(project_path, ".gitignore")
                with open(gitignore_file, "w", encoding="utf-8") as f:
                    f.write(UNITY_GITIGNORE)

                try:
                    subprocess.run(["git", "-C", project_path, "add", ".gitignore"], check=True)
                    subprocess.run(["git", "-C", project_path, "commit", "-m", "Add Unity .gitignore"], check=True)
                except subprocess.CalledProcessError as e:
                    print(f"[Error] .gitignore add/commit 실패: {e}")
                    continue
            else:
                print(f"[INFO] '{project_name}' → 이미 git init 및 .gitignore가 존재합니다.")
        
        if is_test:
            wait()

    print("------------------------------------------------------------")
    print("[INFO] 모든 대상 프로젝트에 대한 Git init 및 .gitignore 설정이 완료되었습니다.")
    print("------------------------------------------------------------")

    # --- 2. 다시 블랙리스트에 포함되지 않은 프로젝트를 순회, Git Clone 수행 ---
    for entry in os.scandir(projects_dir):
        if not entry.is_dir():
            continue

        project_path = entry.path
        project_name = entry.name

        if is_in_blacklist(project_name, blacklist_list):
            continue

        if is_git_repo(project_path):
            clone_target = os.path.join(output_dir, project_name)
            print(f"[INFO] Cloning '{project_name}' → '{clone_target}'")

            # 이미 대상 폴더가 존재하면, 필요에 따라 삭제나 백업 로직을 추가할 수 있음
            # 여기서는 간단히 '이미 있으면 스킵' 로직만 예시로 넣음
            if os.path.exists(clone_target):
                print(f"[WARNING] 대상 폴더가 이미 존재하여 스킵합니다: {clone_target}")
                continue

            try:
                subprocess.run(["git", "clone", project_path, clone_target], check=True)
            except subprocess.CalledProcessError as e:
                print(f"[Error] '{project_name}' clone 실패: {e}")
                continue
        else:
            print(f"[WARNING] '{project_name}'은(는) Git 저장소가 아니므로 clone 불가")
        
        if is_test:
            wait()

    print("------------------------------------------------------------")
    print("[INFO] 스크립트 작업이 모두 완료되었습니다.")
    print("------------------------------------------------------------")


import msvcrt as m
def wait():
    m.getch()


if __name__ == "__main__":
    main()

r"""
# how to run:
```
python main.py `
  --projects_dir "D:/Unity Projects/92. 버림" `
  --output_dir "D:/Unity Project Compressed/92. 버림" `
```

--blacklist "90. 개인 연습,91. 개인 작업,92. 버림,98. Others,AMASSPlayer-main,AMASSPlayer-main_2,AnimationCurveExtractAndRecord,BoneHierarchy,Bowling Scene,Catchball_도형9,Catchball8,GestureNet,IKPlayground,IoTMockUp,J_AMASSPlayer,J_AMASSPlayer6,LeanWalkTest,portals-urp,pun2testforik,ReliableNetworkProject,SentisTest,SMPL2GameRig,SMPLX-Unity,TrigonIK,uma2,VR,VRDemo"
cmd인 경우 ^를 \로 대체
"""